seed: 21

output:
  root_dir: output

dataset:
  name: sbm

  # SBM
  block_size: 10
  nb_blocks: 5
  p: 0.5
  q: 0.05

  # ROC
  nb_cliques: 5
  clique_size: 10

  path: None

preprocessing:
  name: karger
  nb_cuts: 100

algorithm:
  name: core

# -1 in nb_cuts means all
plot:
  cuts: True
  nb_cuts: 10