runs: 1

# allowed types: single, batch
experiment:
  unique_id: 2
  seed: 80
  dataset: BCW
  preprocessing: none
  cut_finding: bin
  cost_function: euclidean_mean
  agreement: 25
  percentile_orders: 80

cost_function:
  nb_points: -1

preprocessing:
  knn:
    k: 14

  rng:
    radius: 0.3

  wknn:
    k: 30

dataset:

  gau_mix:
    sizes: [120, 60, 60]
    centers: [[-2, -2, -2, -2], [2, 2, 2, -2], [2, -2, 2, 2]]
    variances: [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]

  mind:
    mindset_sizes: [100, 50, 50]
    nb_questions: 10
    nb_useless: 50
    noise: 0.1

  moons:
    n_samples: 300
    noise: 0.1
    radius: 0.3

  retinal:
    max_idx: 75

  sbm:
    block_sizes: [50, 75, 100, 100]
    p: 0.3
    q: 0.1

  qst_lkr:
    nb_samples: 1000
    nb_features: 70
    nb_mindsets: 5
    centers: False
    range_answers: [1, 5]

  lfr:
    nb_nodes: 250
    tau1: 3
    tau2: 1.5
    mu: 0.1
    average_degree: 5
    min_community: 20

  BCW:
    _: _

  big5:
    path: datasets/big5.csv

cut_finding:

  linear:
    equations: [[1, 0, 0.5],
                [1, 0, 1],
                [1, 0, -0.5],
                [1, 0, -1],
                [0, 1, -0.5],
                [0, 1, -1],
                [0, 1, 0.5],
                [0, 1, 1]]

  rand_proj:
    nb_cuts: 50
    dimension: 1

  kmeans:
    n_means: 2

  bin:
    n_bins: 20

  coarsening:
    nb_cuts: 300
    n_max: 20

  KL:
    nb_cuts: 40
    lb_f: 0.0
    early_stopping: 10

  FM:
    nb_cuts: 30
    lb_f: 0.2
    early_stopping: False


# -1 in nb_cuts means all
plot:
  no_plots: False
  tree: True
  tangles: False
  cuts: False
  nb_cuts: 10
  soft: True
  hard: False

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3: All
verbose: 3