seed: 21

experiment:
  type: 'single'

output:
  tolerance_predictions: 0.8
  dir: output

algorithm:
  agreement: 40
  name: core

preprocessing:
  name: [kneip, karnig_lin]

  kneip:
    nb_cuts: 500

  karnig_lin:
    nb_cuts: 100
    fractions: [2, 2.5, 3.3, 5, 10]

  local_min:
    nb_cuts: 500

  kmodes:
    max_nb_clusters: 10

  random:
    nb_cuts: 500


tangles:
  percentage_orders: 100

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: True
  nb_cuts: 10