
# allowed types: single, batch
experiment:
  seed: 42
  dataset_name: knn_blobs
  preprocessing_name: random_projection
  agreement: 40
  percentile_orders: 20

dataset:

  moons:
    n_samples: 300
    noise: 0.1
    radius: 0.3

  retinal:
    nb_bins: 10
    max_idx: 75

  sbm:
    block_sizes: [100, 100]
    p: 0.3
    q: 0.1

  knn_blobs:
    blob_sizes: [50, 50, 200, 100]
    blob_centers: [[-2, -2], [2, 2], [-2, 2], [2, -2]]
    blob_variances: [[1, 1], [1, 1], [1, 1], [1, 1]]
    k: 10

  epsilon_blobs:
    blob_sizes: [100, 100]
    blob_centers: [[-2, -2], [2, 2]]
    blob_variances: [[1, 1], [1, 1]]
    radius: 2

  knn_gauss_blobs:
    blob_sizes: [100, 100]
    blob_centers: [[-2, -2], [2, 2]]
    blob_variances: [[1, 1], [1, 1]]
    k: 20

  mindsets:
    mindset_sizes: [100, 50, 50]
    nb_questions: 10
    nb_useless: 5
    noise: 0.1

  q:
    nb_samples: 1000
    nb_features: 70
    nb_mindsets: 5
    centers: False
    range_answers: [1, 5]

  pol_books:
    path_edges: datasets/pol_books/political-books-edges.csv
    path_nodes: datasets/pol_books/political-books-nodes.csv

  cancer:
    nb_bins: 10

  big5:
    path: datasets/big5.csv

  cancer10:
    path: datasets/breast_cancer.csv

  mushrooms:
    path_csv: datasets/mushrooms.csv
    path_yaml: datasets/mushrooms.yaml

  microbiome:
    path: datasets/microbiome.csv
    k: 5
    use_cuts: False
    dual: False

preprocessing:

  random_projection:
    nb_cuts: 50

  linear:
    equations: [[1, 0, 0.5],
                [1, 0, 1],
                [1, 0, -0.5],
                [1, 0, -1],
                [0, 1, -0.5],
                [0, 1, -1],
                [0, 1, 0.5],
                [0, 1, 1]]

  bin_lik:
    n_bins: 5
    range_answers: [0, 5]

  karnig_lin:
    nb_cuts: 50
    lb_f: 0.2

  coarsening:
    nb_cuts: 300
    n_max: 20

  fid_mat:
    nb_cuts: 50
    lb_f: 0.2

# -1 in nb_cuts means all
plot:
  no_plots: False
  tree: True
  tangles: False
  only_leaves: False
  cuts: False
  nb_cuts: 10
  soft: True
  hard: True

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3: All
verbose: 3