seed: 21

output:
  root_dir: output

dataset:
  name: knn
  block_size: 100
  nb_blocks: 2
  p: 0.2
  q: 0.01
  mus: [[0, 0], [0, 2]]
  vars: [[1, 1], [1, 1]]
  k: 5
  path: None

preprocessing:
  name: karger

algorithm:
  name: core

# -1 in nb_cuts means all
plot:
  cuts: True
  nb_cuts: 10