

# allowed types: single, batch
experiment:
  seed: 42
  dataset_name: sbm
  preprocessing_name: karnig_lin
  agreement: 50
  percentile_orders: 100

dataset:
  sbm:
    block_sizes: [100, 100, 100]
    p: 0.3
    q: 0.1

  knn_blobs:
    blob_sizes: [20, 20, 20, 20]
    blob_centers: [[-2, -2], [2, -2], [-2, 2], [2, 2]]
    k: 6

  q_syn:
    n_samples: 100
    n_features: 30
    n_mindsets: 5
    tolerance: 0.10

  big5:
    path: datasets/big5.csv

preprocessing:
  karnig_lin:
    nb_cuts: 100
    lb_f: 0.25

  coarsening:
    nb_cuts: 300
    n_max: 20

  fid_mat:
    nb_cuts: 100
    lb_f: 0.15

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: True
  nb_cuts: 10

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3s: All
verbose: 3