seed: 21

# allowed types: single, batch
experiment:
  type: 'batch'
  dataset_name: sbm

algorithm:
  agreement: 10
  name: core

preprocessing:
  name: karnig_lin

  karnig_lin:
    nb_cuts: 100
    fractions: [2, 3, 4, 5, 6]

tangles:
  percentage_orders: 25

output:
  dir: output

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: True
  nb_cuts: 10

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# #: All
verbose: 1