seed: 21

output:
  root_dir: output

dataset:
  path: datasets/big5.csv
  name: sbm

  knn:
    block_size: 10
    nb_blocks: 2
    mus: [[0, 0], [0, 2]]
    vars: [[1, 1], [1, 1]]
    k: 5

  sbm:
    block_size: 20
    nb_blocks: 5
    p: 0.5
    q: 0.1

  roc:
    nb_cliques: 20
    clique_size: 10

  q_syn:
    n_samples: 100
    n_features: 30
    n_mindsets: 5
    tolerance: 0.10

algorithm:
  min_size: 12
  name: core

preprocessing:
  name: karnig_lin

  kneip:
    nb_cuts: 501

  karnig_lin:
    nb_cuts: 30
    fractions: [2, 3, 4, 5]

  karger:
    nb_cuts: 100

  fast_min_cut:
    nb_cuts: 10

  neighbours:
    nb_cuts: 1000
    percentages: [0.2, 0.3, 0.4, 0.5]

  random:
    min_size_cover: 100
    dim_linspace: 5

  kmodes:
    max_nb_clusters: 10

tangles:
  percentage_cuts: 0.2

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: True
  nb_cuts: 10