
# allowed types: single, batch
experiment:
  seed: 42
  dataset_name: knn_blobs
  preprocessing_name: fid_mat
  agreement: 40
  percentile_orders: 100

dataset:

  retinal:
    nb_bins: 10
    max_idx: 75

  sbm:
    block_sizes: [100, 100]
    p: 0.64
    q: 0.41

  knn_blobs:
    blob_sizes: [120, 60, 60]
    blob_centers: [[-1, 0], [1, -1], [1, 1]]
    k: 10

  mindsets:
    mindset_sizes: [10, 10]
    nb_questions: 10
    nb_useless: 0
    noise: 0

  q:
    nb_samples: 1000
    nb_features: 70
    nb_mindsets: 5
    centers: False
    range_answers: [1, 10]

  pol_books:
    path_edges: datasets/pol_books/political-books-edges.csv
    path_nodes: datasets/pol_books/political-books-nodes.csv

  cancer:
    nb_bins: 5

  big5:
    path: datasets/big5.csv

  cancer10:
    path: datasets/breast_cancer.csv

  mushrooms:
    path_csv: datasets/mushrooms.csv
    path_yaml: datasets/mushrooms.yaml

preprocessing:
  bin_lik:
    range_answers: [1, 10]

  karnig_lin:
    nb_cuts: 100
    lb_f: 0.3

  coarsening:
    nb_cuts: 300
    n_max: 20

  fid_mat:
    nb_cuts: 2
    lb_f: 0.2

# -1 in nb_cuts means all
plot:
  no_plots: false
  tree: True
  tangles: False
  cuts: False
  nb_cuts: 10
  soft: True
  hard: True

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3: All
verbose: 3