big5:
  path: datasets/big5.csv

sbm:
  block_sizes: [100, 100, 100]
  p: 0.3
  q: 0.1

knn_blobs:
  blob_sizes: [20, 20, 20, 20]
  blob_centers: [[-1.5, -1.5], [1.5, -1.5], [-1.5, 1.5], [1.5, 1.5]]
  k: 6

multilevel:
  block_size: [20, 10]
  p_in: [0.5, 1]
  p_out: 0.05

roc:
  nb_cliques: 20
  clique_size: 10

q_syn:
  n_samples: 100
  n_features: 30
  n_mindsets: 5
  tolerance: 0.10
