
# allowed types: single, batch
experiment:
  seed: 30
  dataset_name: blobs
  preprocessing_name: bin_lik
  agreement: 20
  percentile_orders: 100

dataset:

  moons:
    n_samples: 300
    noise: 0.1
    radius: 0.3

  retinal:
    nb_bins: 10
    max_idx: 75

  sbm:
    block_sizes: [50, 75, 100, 100]
    p: 0.3
    q: 0.1

  blobs:
    blob_sizes: [60, 60, 60, 60]
    blob_centers: [[-2, -2], [-2, 2], [2, -2], [2, 2]]
    k: 20
    blob_variances: [[1, 1], [1, 1], [1, 1], [1, 1]]

  gblobs:
    blob_sizes: [60, 60, 60, 60]
    blob_centers: [[-2, -2], [-2, 2], [2, -2], [2, 2]]
    k: 24
    sigma: [[1, 1], [1, 1], [1, 1], [1, 1]]


  mindsets:
    mindset_sizes: [500, 500]
    nb_questions: 20
    nb_useless: 0
    noise: 0.2

  q:
    nb_samples: 1000
    nb_features: 70
    nb_mindsets: 5
    centers: False
    range_answers: [1, 5]

  lfr:
    nb_nodes: 250
    tau1: 3
    tau2: 1.5
    mu: 0.1
    average_degree: 5
    min_community: 20

  cancer:
    nb_bins: 10

  big5:
    path: datasets/big5.csv

  wawe:
    path: 

  cancer10:
    path: datasets/breast_cancer.csv

  mushrooms:
    path_csv: datasets/mushrooms.csv
    path_yaml: datasets/mushrooms.yaml

preprocessing:

  linear:
    equations: [[1, 0, 0.5],
                [1, 0, 1],
                [1, 0, -0.5],
                [1, 0, -1],
                [0, 1, -0.5],
                [0, 1, -1],
                [0, 1, 0.5],
                [0, 1, 1]]

  bin_lik:
    n_bins: 20
    range_answers: [1, 20]

  karnig_lin:
    nb_cuts: 100
    lb_f: 0.1

  coarsening:
    nb_cuts: 300
    n_max: 20

  fid_mat:
    nb_cuts: 30
    lb_f: 0.1

# -1 in nb_cuts means all
plot:
  no_plots: False
  tree: True
  tangles: False
  cuts: False
  nb_cuts: 10
  soft: True
  hard: True

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3: All
verbose: 3