

# allowed types: single, batch
experiment:
  seed: 42
  dataset_name: cancer10
  preprocessing_name: feat
  agreement: 20
  percentile_orders: 100

dataset:
  sbm:
    block_sizes: [100, 100, 100]
    p: 0.3
    q: 0.1

  knn_blobs:
    blob_sizes: [20, 20, 20, 20]
    blob_centers: [[-2, -2], [2, -2], [-2, 2], [2, 2]]
    k: 6

  q_syn:
    n_samples: 100
    n_features: 60
    n_mindsets: 6
    n_mistakes: 5

  pol_books:
    path_edges: datasets/pol_books/political-books-edges.csv
    path_nodes: datasets/pol_books/political-books-nodes.csv

  big5:
    path: datasets/big5.csv

  cancer10:
    path: datasets/breast_cancer.csv

preprocessing:
  karnig_lin:
    nb_cuts: 300
    lb_f: 0.2

  coarsening:
    nb_cuts: 300
    n_max: 20

  fid_mat:
    nb_cuts: 300
    lb_f: 0.1

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: False
  nb_cuts: 10

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3: All
verbose: 3