seed: 21

# allowed types: single, batch
experiment:
  type: 'single'

output:
  tolerance_predictions: 0.8
  dir: output

algorithm:
  min_size: 10
  name: core

preprocessing:
  name: karnig_lin

  karnig_lin:
    nb_cuts: 100
    fractions: [2, 3, 4, 5, 6, 7, 8, 9, 10]

tangles:
  percentage_cuts: 0.1

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: False
  nb_cuts: 10