
# allowed types: single, batch
experiment:
  seed: 42
  dataset_name: sbm
  preprocessing_name: fid_mat
  agreement: 3
  percentile_orders: 100

dataset:
  sbm:
    block_sizes: [10, 5, 5]
    p: 0.3
    q: 0.1

  knn_blobs:
    blob_sizes: [50, 50, 50, 50]
    blob_centers: [[-2, -2], [2, -2], [-2, 2], [2, 2]]
    k: 10

  mindsets:
    mindset_sizes: [100, 100]
    nb_questions: 3
    nb_useless: 0
    noise: 0.2

  q:
    nb_samples: 1000
    nb_features: 60
    nb_mindsets: 6
    range_answers: [1, 10]

  pol_books:
    path_edges: datasets/pol_books/political-books-edges.csv
    path_nodes: datasets/pol_books/political-books-nodes.csv

  cancer:
    nb_bins: 5

  big5:
    path: datasets/big5.csv

  cancer10:
    path: datasets/breast_cancer.csv

  mushrooms:
    path_csv: datasets/mushrooms.csv
    path_yaml: datasets/mushrooms.yaml

preprocessing:
  bin_lik:
    range_answers: [1, 10]

  karnig_lin:
    nb_cuts: 100
    lb_f: 0.3

  coarsening:
    nb_cuts: 300
    n_max: 20

  fid_mat:
    nb_cuts: 10
    lb_f: 0.1

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: False
  nb_cuts: 10

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3: All
verbose: 3