runs: 1

# allowed types: single, batch
experiment:
  unique_id: 2
  seed: 10
  dataset: moons
  preprocessing: wknn
  cut_finding: KL
  cost_function: cut_mean
  agreement: 70
  percentile_orders: 100
  prune_depth: 1
  nb_sample_points: 0

preprocessing:
  knn:
    k: 10

  rng:
    radius: 0.3

  wknn:
    k: 50

dataset:

  gau_mix:
    sizes: [2000, 1000, 2000, 1000]
    centers: [[-3, -2], [-3, 3], [3, 3], [3, -2]]
    variances: [[1,2],[1, 0.8], [1,2], [1, 0.8]]

#  gau_mix:
#    sizes: [150, 150, 150, 350, 200]
#    centers: [[-2,-7],[-2,0],[-2,7],[8,5],[8,-6]]
#    variances: [[2,2],[2.5,1.2],[2,2],[1.6,3],[1.5,2]]

  mind:
    mindset_sizes: [200, 300, 200]
    nb_questions: 10
    nb_useless: 5
    noise: 0.1

  moons:
    n_samples: 300
    noise: 0.1

  circles:
    n_samples: 300
    noise: 0.05
    factor: 0.5

  retinal:
    max_idx: 75

  sbm:
    block_sizes: [50, 50]
    p: 0.3
    q: 0.1

  qst_lkr:
    nb_samples: 1000
    nb_features: 70
    nb_mindsets: 5
    centers: False
    range_answers: [1, 5]

  lfr:
    nb_nodes: 250
    tau1: 3
    tau2: 1.5
    mu: 0.1
    average_degree: 5
    min_community: 20

  BCW:
    _: _

  big5:
    path: datasets/big5.csv

cut_finding:

  linear:
    equations: [[1, 0, 0.5],
                [1, 0, 1],
                [1, 0, -0.5],
                [1, 0, -1],
                [0, 1, -0.5],
                [0, 1, -1],
                [0, 1, 0.5],
                [0, 1, 1]]

  rand_proj:
    nb_cuts: 25
    dimension: 1

  kmeans:
    n_means: 2

  bin:
    n_bins: 20

  coarsening:
    nb_cuts: 300
    n_max: 20

  KL:
    nb_cuts: 25
    lb_f: 0.2
    early_stopping: 5

  FM:
    nb_cuts: 30
    lb_f: 0.2
    early_stopping: 10

# -1 in nb_cuts means all
plot:
  no_plots: False
  tree: True
  tangles: False
  cuts: True
  nb_cuts: 10
  soft: True
  hard: False

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# 3: All
verbose: 3