seed: 21

output:
  root_dir: output

dataset:
  name: sbm
  path: datasets/big5.csv

  sbm:
    block_size: 10
    nb_blocks: 3
    p: 0.9
    q: 0.2

  roc:
    nb_cliques: 5
    clique_size: 10

  q_syn:
    n_samples: 100
    n_features: 30
    n_mindsets: 5
    tolerance: 0.10

algorithm:
  min_size: 8
  name: core

preprocessing:
  name: random
  nb_cuts: 10

  random:
    min_size_cover: 100
    dim_linspace: 5

  kmodes:
    max_nb_clusters: 10

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: True
  nb_cuts: -1