seed: 21

output:
  root_dir: output

dataset:
  name: q_syn
  path: datasets/big5.csv

  sbm:
    block_size: 10
    nb_blocks: 5
    p: 0.5
    q: 0.05

  roc:
    nb_cliques: 5
    clique_size: 10

  q_syn:
    n_samples: 100
    n_features: 30
    n_mindsets: 5
    tolerance: 0.10

algorithm:
  min_size: 10
  name: core

preprocessing:
  name: kmodes
  nb_cuts: 100

  kmodes:
    max_nb_clusters: 10

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: False
  nb_cuts: 10