seeds: [21, 42]

# allowed types: single, batch
experiment:
  dataset_name: sbm

big5:
  path: datasets/big5.csv

dataset:
  sbm:
    block_sizes: [40, 80]
    ps: [0.2]
    qs: [0.02]

  knn_blobs:
    blob_sizes: [20, 20, 20, 20]
    blobs_centers: [[[-1.5, -1.5], [1.5, -1.5], [-1.5, 1.5], [1.5, 1.5]]]
    ks: [6]

  q_syn:
    n_samples: 100
    n_features: 30
    n_mindsets: 5
    tolerance: 0.10

algorithm:
  agreement: 5
  name: core

preprocessing:
  name: fid_mat

  karnig_lin:
    nb_cuts: 100
    fractions: [2, 3]

  coarsening:
    nb_cuts: 300
    n_max: 20

  fid_mat:
    nb_cuts: 20
    ratio: 0.2

tangles:
  percentage_orders: 25

# -1 in nb_cuts means all
plot:
  tangles: True
  cuts: True
  nb_cuts: -1

# 0, 1, 2, 3 allowed
# 0: Nothing
# 1: Only batch info
# 2: All but cuts finding infos
# #: All
verbose: 3