
big5:
  path: datasets/big5.csv

sbm:
  block_size: 20
  nb_blocks: 4
  p: 0.5
  q: 0.03

knn_blobs:
  blob_sizes: [30, 30, 30]
  blob_centers: [[-3, -3], [0, 0], [3, 3]]
  k: 5


multilevel:
  block_size: [20, 10]
  p_in: [0.5, 1]
  p_out: 0.05


roc:
  nb_cliques: 20
  clique_size: 10

q_syn:
  n_samples: 100
  n_features: 30
  n_mindsets: 5
  tolerance: 0.10
